### ISSUE TITLE
Original version of alunar firmware

### ISSUE THREAD

**Issue by jcj99be** [camalot/alunar-prusa-i3-marlin-i3-firmware#1]
Hello,

Sorry to contact you this way, but I didn't find a way to contact you except via issue submission... 
You mention that this is the firmware that came with your alunar prusa i3. 

I have recently purchased the alunar m508... I wanted to make some modifications to enable auto leveling, but the SD card that was delivered with the package is damaged and is unreadable. So, I don't have any baseline for the firmware (don't even know what version is actually installed). So, I'm afraid to flash anything if I can't get back to the original version in case of a problem... 

So, I was wondering if the version you have here would work with the m508? I see you have already brought it up to the latest marlin version. Do you also have the original version delivered on the SD card (in fact, do you have the content of the original SD card)?

**Comment by camalot** [comment]
Basically, this project is "upstream" marlin. the only real difference is what is in `Marlin_I3/Configuration_Alunar.h` and `Marlin_I3/Configuration_Alunar_adv.h`.

I believe the M508 is considered the prusa i3 clone as I have seen others are using this project on the m508. Except it sounds like there have been further improvements for auto bed leveling and such. This project is current (or close to current) with upstream Marlin, so you should be able to enable the functionality. 

You can find the Bed Leveling settings in [Configuration.h](https://github.com/camalot/alunar-prusa-i3-marlin-i3-firmware/blob/develop/Marlin_I3/Configuration.h#L835). 

What I would do is find the settings that I need to change, and put them in the `Configuration_Alunar.h`, leaving the other file in the "default" state.
